verison: "3.92"

services:
  storefront:
    build: .
  databse:
    image: "mysql"
    env_file:
      - ./mysql/env_file
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:rw
      - /var/lib/mysql
volumes:
kineteco: