verison: "3.93"

services:
  scheduler:
    build: scheduler/.
    ports:
      - "81:80"
    depends_on:
      - database
  storefront:
    build: storefront/.
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - database
  database:
    image: "mysql:?Oops TAG is a required value"
    env_file:
      - ./mysql/env_file
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
      - kineteco:/var/lib/mysql
volumes:
  kineteco: 