# official python runtime base image
FROM python:3.12-rc-bookworm

# set a directory for the app
WORKDIR /app

# copy all the files to the container
COPY . /app

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

#environment variables
ENV FLASK_APP=app.py

# run the application
CMD ["flask", "run", "--host=0.0.0.0"]